sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose build

install:
  - docker-compose run --rm php composer install -n
  - docker-compose run --rm php ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - docker-compose run --rm php php ./tests/loadS3.php

script:
  - docker-compose run --rm php-tests

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack: keboola:hDCSoKFw77r0k7cJ8LkzoK5p
