version: "2"
services:
  dev:
    build: .
    image: keboola/ex-aws-s3
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - AWS_S3_BUCKET
      - AWS_REGION
      - ACCOUNT_ID
      - ROLE_NAME
      - KBC_PROJECTID
      - KBC_STACKID
      - KEBOOLA_USER_AWS_ACCESS_KEY
      - KEBOOLA_USER_AWS_SECRET_KEY
      - UPLOAD_USER_AWS_ACCESS_KEY
      - UPLOAD_USER_AWS_SECRET_KEY
      - DOWNLOAD_USER_AWS_ACCESS_KEY
      - DOWNLOAD_USER_AWS_SECRET_KEY
