version: "2"
services:
  php:
    build: .
    image: keboola/s3-extractor
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    environment:
      - AWS_S3_BUCKET
      - AWS_REGION
      - PREPARE_TESTS_AWS_ACCESS_KEY
      - PREPARE_TESTS_AWS_SECRET_KEY
  php-tests:
    image: keboola/s3-extractor
    command: >
             sh -c '
             ./tests.sh
             '
    volumes:
      - ./:/code
    environment:
      - AWS_S3_BUCKET
      - AWS_REGION
      - TESTS_AWS_ACCESS_KEY
      - TESTS_AWS_SECRET_KEY

  php-code-coverage:
    build:
      context: .
      dockerfile: ./docker/dockerfile/code-coverage
    image: keboola/s3-extractor-code-coverage
    command: >
             sh -c '
             ./code-coverage.sh
             '
    volumes:
      - ./:/code
    environment:
      - AWS_S3_BUCKET
      - AWS_REGION
      - TESTS_AWS_ACCESS_KEY
      - TESTS_AWS_SECRET_KEY
      - CODECLIMATE_REPO_TOKEN
